#!/bin/bash

if [ `id -u` -ne 0 ]; then
	echo "Error: You must be root to run this script!"
	exit 1
fi

ADMIN_FOLDER="./admin"

if [ $# -eq 0 ] ; then
#   Первоначальная настройка сервера
    . "$ADMIN_FOLDER/init.sh"
else
#   Администрирование
	. "$ADMIN_FOLDER/admin.sh"