#!/bin/bash

ADMIN_FOLDER="./admin"
MODULE_FOLDER="./modules"

if [ $# -eq 0 ] ; then
#   Первоначальная настройка сервера
    . "$ADMIN_FOLDER/init.sh"
else
#   Администрирование
	. "$MODULE_FOLDER/admin.sh"